export const CLEAR_ERROR = 'CLEAR_ERROR';

export const  REGISTER_USER_REQ = 'REGISTER_USER_REQ';
export const  REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const  REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const  LOGIN_REQ = 'LOGIN_REQ';
export const  LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const  LOGIN_ERROR = 'LOGIN_ERROR';

export const  LOAD_USER_REQ = 'LOAD_USER_REQ';
export const  LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const  LOAD_USER_ERROR = 'LOAD_USER_ERROR';

export const  LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const  LOGOUT_ERROR = 'LOGOUT_ERROR';

export const  UPDATE_PROFILE_REQ = 'UPDATE_PROFILE_REQ';
export const  UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const  UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET';
export const  UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const  UPDATE_PASSWORD_REQ = 'UPDATE_PASSWORD_REQ';
export const  UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const  UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET';
export const  UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR';

export const  FORGOT_PASSWORD_REQ = 'FORGOT_PASSWORD_REQ';
export const  FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const  FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

export const  NEW_PASSWORD_REQ = 'NEW_PASSWORD_REQ';
export const  NEW_PASSWORD_SUCCESS = 'NEW_PASSWORD_SUCCESS';
export const  NEW_PASSWORD_ERROR = 'NEW_PASSWORD_ERROR';

export const  ALL_USERS_REQ = 'ALL_USERS_REQ';
export const  ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS';
export const  ALL_USERS_ERROR = 'ALL_USERS_ERROR';

export const  UPDATE_USER_REQ = 'UPDATE_USER_REQ';
export const  UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const  UPDATE_USER_RESET = 'UPDATE_USER_RESET';
export const  UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const GET_USER_DETAILS_REQ = 'GET_USER_DETAILS_REQ';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_ERROR = 'GET_USER_DETAILS_ERROR';

export const DELETE_USER_REQ = 'DELETE_USER_REQ';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';