export const CLEAR_ERROR = 'CLEAR_ERROR';

export const  CREATE_ORDER_REQ = 'CREATE_ORDER_REQ';
export const  CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const  CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';

export const  MY_ORDERS_REQ = 'MY_ORDERS_REQ';
export const  MY_ORDERS_SUCCESS = 'MY_ORDERS_SUCCESS';
export const  MY_ORDERS_ERROR = 'MY_ORDERS_ERROR';

export const  ORDER_DETAILS_REQ = 'ORDER_DETAILS_REQ';
export const  ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const  ORDER_DETAILS_ERROR = 'ORDER_DETAILS_ERROR';

export const  ADMIN_ALL_ORDERS_REQ = 'ADMIN_ALL_ORDERS_REQ';
export const  ADMIN_ALL_ORDERS_SUCCESS = 'ADMIN_ALL_ORDERS_SUCCESS';
export const  ADMIN_ALL_ORDERS_ERROR = 'ADMIN_ALL_ORDERS_ERROR';

export const  ADMIN_UPDATE_ORDER_REQ = 'ADMIN_UPDATE_ORDERS_REQ';
export const  ADMIN_UPDATE_ORDER_SUCCESS = 'ADMIN_UPDATE_ORDERS_SUCCESS';
export const  ADMIN_UPDATE_ORDER_ERROR = 'ADMIN_UPDATE_ORDERS_ERROR';

export const  ADMIN_DELETE_ORDER_REQ = 'ADMIN_DELETE_ORDERS_REQ';
export const  ADMIN_DELETE_ORDER_SUCCESS = 'ADMIN_DELETE_ORDERS_SUCCESS';
export const  ADMIN_DELETE_ORDER_ERROR = 'ADMIN_DELETE_ORDERS_ERROR';