export const CLEAR_ERROR = 'CLEAR_ERROR';

export const  GET_ALL_PRODUCT_REQ = 'GET_ALL_PRODUCT_REQ';
export const  GET_ALL_PRODUCT_SUCCESS = 'GET_ALL_PRODUCT_SUCCESS';
export const  GET_ALL_PRODUCT_ERROR = 'GET_ALL_PRODUCT_ERROR';


export const  GET_PRODUCT_DETAIL_REQ = 'GET_PRODUCT_DETAIL_REQ';
export const  GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS';
export const  GET_PRODUCT_DETAIL_ERROR = 'GET_PRODUCT_DETAIL_ERROR';

export const  NEW_REVIEW_REQ = 'NEW_REVIEW_REQ';
export const  NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS';
export const  NEW_REVIEW_RESET = 'NEW_REVIEW_RESET';
export const  NEW_REVIEW_ERROR = 'NEW_REVIEW_ERROR';

export const  ADMIN_PRODUCT_REQ = 'ADMIN_PRODUCT_REQ';
export const  ADMIN_PRODUCT_SUCCESS = 'ADMIN_PRODUCT_SUCCESS';
export const  ADMIN_PRODUCT_ERROR = 'ADMIN_PRODUCT_ERROR';

export const  ADMIN_CREATE_PRODUCT_REQ = 'ADMIN_CREATE_PRODUCT_REQ';
export const  ADMIN_CREATE_PRODUCT_SUCCESS = 'ADMIN_CREATE_PRODUCT_SUCCESS';
export const  ADMIN_CREATE_PRODUCT_ERROR = 'ADMIN_CREATE_PRODUCT_ERROR';

export const  ADMIN_DELETE_PRODUCT_REQ = 'ADMIN_DELETE_PRODUCT_REQ';
export const  ADMIN_DELETE_PRODUCT_SUCCESS = 'ADMIN_DELETE_PRODUCT_SUCCESS';
export const  ADMIN_DELETE_PRODUCT_ERROR = 'ADMIN_DELETE_PRODUCT_ERROR';

export const  ADMIN_UPDATE_PRODUCT_REQ = 'ADMIN_UPDATE_PRODUCT_REQ';
export const  ADMIN_UPDATE_PRODUCT_SUCCESS = 'ADMIN_UPDATE_PRODUCT_SUCCESS';
export const  ADMIN_UPDATE_PRODUCT_ERROR = 'ADMIN_UPDATE_PRODUCT_ERROR';

export const  GET_REVIEWS_PRODUCT_REQ = 'GET_REVIEWS_PRODUCT_REQ';
export const  GET_REVIEWS_PRODUCT_SUCCESS = 'GET_REVIEWS_PRODUCT_SUCCESS';
export const  GET_REVIEWS_PRODUCT_ERROR = 'GET_REVIEWS_PRODUCT_ERROR';

export const  DELETE_REVIEW_REQ = 'DELETE_REVIEW_REQ';
export const  DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const  DELETE_REVIEW_ERROR = 'DELETE_REVIEW_ERROR';
export const  DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET';